name: about_dependencies
description: Automatically generate dart file with informations about used dependencies in pubspec.yaml.
version: 0.0.1
homepage: https://github.com/Supercaly/about_dependencies
repository: https://github.com/Supercaly/about_dependencies/tree/master/about_dependencies_generator

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  pubspec_parse: ^0.1.5
  dio: ^3.0.9
  args: ^1.5.2
  path: ^1.7.0
  code_builder: ^3.3.0
  dart_style: ^1.3.6

dev_dependencies:
  test: ^1.14.6
