targets:
  $default:
    builders:
      about_dependencies:
        enabled: true

builders:
  about_dependencies:
    import: "package:about_dependencies/builder.dart"
    builder_factories: ["aboutDependencies"]
    build_extensions: {".dart": [".about_dependencies.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]