name: about_dependencies
description: A new Flutter package.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  build: ^1.3.0
  source_gen: ^0.9.5
  pubspec_yaml: ^2.0.1
  dio: ^3.0.9

dev_dependencies:
  build_test: ^1.2.0
  build_runner: ^1.10.0
  test: ^1.14.6
