name: about_dependencies
description: Automatically generate dart file with informations about used dependencies in pubspec.yaml.
version: 0.0.1
homepage:
repository:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  build: ^1.3.0
  source_gen: ^0.9.5
  pubspec_parse: ^0.1.5
  dio: ^3.0.9
  path: ^1.7.0
  code_builder: ^3.3.0
  dart_style: ^1.3.6

dev_dependencies:
  build_test: ^1.2.0
  build_runner: ^1.10.0
  test: ^1.14.6
